cat2label = {
    'person': ['person'],
    'traffic': [
        'bicycle',
        'car',
        'motorcycle',
        'airplane',
        'bus',
        'train',
        'truck',
        'boat',
        'traffic light',
        'fire hydrant',
        'stop sign',
        'parking meter'
    ],
    'animal': [
        'bird',
        'cat',
        'dog',
        'horse',
        'sheep',
        'cow',
        'elephant',
        'bear',
        'zebra',
        'giraffe'
    ],
    'accessories': [
        'backpack',
        'umbrella',
        'handbag',
        'tie',
        'suitcase'
    ],
    'sport tools': [
        'frisbee',
        'skis',
        'snowboard',
        'sports ball',
        'kite',
        'baseball bat',
        'baseball glove',
        'skateboard',
        'surfboard',
        'tennis racket'
    ],
    'utensils': [
        'bottle',
        'wine glass',
        'cup',
        'fork',
        'knife',
        'spoon',
        'bowl'
    ],
    'food': [
        'banana',
        'apple',
        'sandwich',
        'orange',
        'broccoli',
        'carrot',
        'hot dog',
        'pizza',
        'donut',
        'cake'
    ],
    'furniture': [
        'bench',
        'chair',
        'couch',
        'potted plant',
        'bed',
        'dining table',
        'toilet',
        'book',
        'clock',
        'vase',
        'teddy bear'
    ],
    'tech': [
        'tv',
        'laptop',
        'mouse',
        'remote',
        'keyboard',
        'cell phone'
    ],
    'kitchen': [
        'microwave',
        'oven',
        'toaster',
        'sink',
        'refrigerator',
        'scissors'
    ],
    'personal care': [
        'hair drier',
        'toothbrush'    
    ]
}

label2cat = {
    'person': 'person',
    'bicycle':'traffic' ,
    'car':'traffic' ,
    'motorcycle':'traffic' ,
    'airplane':'traffic' ,
    'bus':'traffic' ,
    'train':'traffic' ,
    'truck':'traffic' ,
    'boat':'traffic' ,
    'traffic light':'traffic' ,
    'fire hydrant':'traffic' ,
    'stop sign':'traffic' ,
    'parking meter':'traffic' ,
    'bird':'animal' ,
    'cat':'animal' ,
    'dog':'animal' ,
    'horse':'animal' ,
    'sheep':'animal' ,
    'cow':'animal' ,
    'elephant':'animal' ,
    'bear':'animal' ,
    'zebra':'animal' ,
    'giraffe':'animal' ,
    'backpack':'accessories' ,
    'umbrella':'accessories' ,
    'handbag':'accessories' ,
    'tie':'accessories' ,
    'suitcase':'accessories' ,
    'frisbee':'sport tools' ,
    'skis':'sport tools' ,
    'snowboard':'sport tools' ,
    'sports ball':'sport tools' ,
    'kite':'sport tools' ,
    'baseball bat':'sport tools' ,
    'baseball glove':'sport tools' ,
    'skateboard':'sport tools' ,
    'surfboard':'sport tools' ,
    'tennis racket':'sport tools' ,
    'bottle':'utensils' ,
    'wine glass':'utensils' ,
    'cup':'utensils' ,
    'fork':'utensils' ,
    'knife':'utensils' ,
    'spoon':'utensils' ,
    'bowl':'utensils' ,
    'banana':'food' ,
    'apple':'food' ,
    'sandwich':'food' ,
    'orange':'food' ,
    'broccoli':'food' ,
    'carrot':'food' ,
    'hot dog':'food' ,
    'pizza':'food' ,
    'donut':'food' ,
    'cake':'food' ,
    'bench':'furniture' ,
    'chair':'furniture' ,
    'couch':'furniture' ,
    'potted plant':'furniture' ,
    'bed':'furniture' ,
    'dining table':'furniture' ,
    'toilet':'furniture' ,
    'book':'furniture' ,
    'clock':'furniture' ,
    'vase':'furniture' ,
    'teddy bear':'furniture' ,
    'tv':'tech' ,
    'laptop':'tech' ,
    'mouse':'tech' ,
    'remote':'tech' ,
    'keyboard':'tech' ,
    'cell phone':'tech' ,
    'microwave':'kitchen' ,
    'oven':'kitchen' ,
    'toaster':'kitchen' ,
    'sink':'kitchen' ,
    'refrigerator':'kitchen' ,
    'scissors':'kitchen' ,
    'hair drier':'personal care' ,
    'toothbrush':'personal care' 
}