const spaceList = [
    "aquarium-thủy cung",
    "aqueduct-cầu dẫn nước",
    "arcade-phòng trò chơi",
    "arch-vòm",
    "archaelogical_excavation-khai quật khảo cổ",
    "archive-lưu trữ",
    "arena/hockey-sân thi đấu khúc côn cầu",
    "arena/performance-đấu trường biểu diễn",
    "arena/rodeo-đấu trường rodeo",
    "army_base-căn cứ quân đội",
    "art_gallery-phòng trưng bày nghệ thuật",
    "art_school-trường mỹ thuật",
    "art_studio-xưởng nghệ thuật",
    "artists_loft-căn gác nghệ sĩ",
    "assembly_line-dây chuyền sản xuất",
    "athletic_field/outdoor-sân thể thao ngoài trời",
    "atrium/public-sảnh lớn công cộng",
    "attic-gác mái",
    "auditorium-giảng đường, hội trường",
    "auto_factory-nhà máy sản xuất ô tô",
    "auto_showroom-phòng trưng bày ô tô",
    "badlands-vùng đất khô cằn",
    "bakery/shop-tiệm bánh",
    "balcony/exterior-ban công ngoài trời",
    "balcony/interior-ban công trong nhà",
    "ball_pit-hố bóng",
    "ballroom-phòng khiêu vũ",
    "bamboo_forest-rừng tre",
    "bank_vault-hầm chứa ngân hàng",
    "banquet_hall-phòng tiệc",
    "bar-quán bar",
    "barn-nhà kho, chuồng gia súc",
    "barndoor-cửa chuồng",
    "baseball_field-sân bóng chày",
    "basement-tầng hầm",
    "basketball_court/indoor-sân bóng rổ trong nhà",
    "bathroom-phòng tắm",
    "bazaar/indoor-chợ trong nhà",
    "bazaar/outdoor-chợ ngoài trời",
    "beach-bãi biển",
    "beach_house-nhà trên bãi biển",
    "beauty_salon-tiệm làm đẹp",
    "bedchamber-phòng ngủ",
    "bedroom-phòng ngủ",
    "beer_garden-vườn bia",
    "beer_hall-hội trường bia",
    "berth-giường trên tàu",
    "biology_laboratory-phòng thí nghiệm sinh học",
    "boardwalk-lối đi bộ bằng gỗ",
    "boat_deck-boong tàu",
    "boathouse-nhà thuyền",
    "bookstore-hiệu sách",
    "booth/indoor-gian hàng trong nhà",
    "botanical_garden-vườn bách thảo",
    "bow_window/indoor-cửa sổ lồi trong nhà",
    "bowling_alley-đường chơi bowling",
    "boxing_ring-võ đài",
    "bridge-cầu",
    "building_facade-mặt tiền tòa nhà",
    "bullring-đấu trường bò tót",
    "burial_chamber-hầm mộ",
    "bus_interior-bên trong xe buýt",
    "bus_station/indoor-nhà ga xe buýt",
    "butchers_shop-cửa hàng bán thịt",
    "butte-đồi đá",
    "cabin/outdoor-nhà gỗ ngoài trời",
    "cafeteria-quán ăn tự phục vụ",
    "campsite-khu cắm trại",
    "campus-khuôn viên trường",
    "canal/natural-kênh tự nhiên",
    "canal/urban-kênh đô thị",
    "candy_store-cửa hàng kẹo",
    "canyon-hẻm núi",
    "car_interior-bên trong xe hơi",
    "carrousel-vòng quay ngựa gỗ",
    "castle-lâu đài",
    "catacomb-hầm mộ dưới đất",
    "cemetery-nghĩa trang",
    "chalet-nhà gỗ kiểu Thụy Sĩ",
    "chemistry_lab-phòng thí nghiệm hóa học",
    "childs_room-phòng trẻ em",
    "church/indoor-nhà thờ trong nhà",
    "church/outdoor-nhà thờ ngoài trời",
    "classroom-phòng học",
    "clean_room-phòng sạch",
    "cliff-vách đá",
    "closet-tủ đồ",
    "clothing_store-cửa hàng quần áo",
    "coast-bờ biển",
    "cockpit-buồng lái",
    "coffee_shop-quán cà phê",
    "computer_room-phòng máy tính",
    "conference_center-trung tâm hội nghị",
    "conference_room-phòng họp",
    "construction_site-công trường xây dựng",
    "corn_field-cánh đồng ngô",
    "corral-chuồng gia súc",
    "corridor-hành lang",
    "cottage-nhà tranh",
    "courthouse-tòa án",
    "courtyard-sân trong",
    "creek-con suối",
    "crevasse-khe nứt",
    "crosswalk-vạch qua đường",
    "dam-đập nước",
    "delicatessen-cửa hàng bán đồ ăn sẵn",
    "department_store-cửa hàng bách hóa",
    "desert/sand-sa mạc cát",
    "desert/vegetation-sa mạc có cây cối",
    "desert_road-con đường sa mạc",
    "diner/outdoor-quán ăn ngoài trời",
    "dining_hall-phòng ăn lớn",
    "dining_room-phòng ăn",
    "discotheque-vũ trường",
    "doorway/outdoor-cửa ngoài",
    "dorm_room-phòng ký túc xá",
    "downtown-trung tâm thành phố",
    "dressing_room-phòng thay đồ",
    "driveway-lối xe vào nhà",
    "drugstore-nhà thuốc",
    "elevator/door-cửa thang máy",
    "elevator_lobby-sảnh thang máy",
    "elevator_shaft-giếng thang máy",
    "embassy-đại sứ quán",
    "engine_room-phòng động cơ",
    "entrance_hall-sảnh vào",
    "escalator/indoor-thang cuốn trong nhà",
    "excavation-khai quật",
    "fabric_store-cửa hàng vải",
    "farm-nông trại",
    "fastfood_restaurant-nhà hàng ăn nhanh",
    "field/cultivated-cánh đồng canh tác",
    "field/wild-cánh đồng hoang dã",
    "field_road-đường đồng",
    "fire_escape-lối thoát hiểm",
    "fire_station-trạm cứu hỏa",
    "fishpond-ao cá",
    "flea_market/indoor-chợ trời trong nhà",
    "florist_shop/indoor-cửa hàng hoa trong nhà",
    "food_court-khu ẩm thực",
    "football_field-sân bóng đá",
    "forest/broadleaf-rừng rậm",
    "forest_path-đường mòn trong rừng",
    "forest_road-đường rừng",
    "formal_garden-vườn cảnh",
    "fountain-đài phun nước",
    "galley-nhà bếp trên tàu",
    "garage/indoor-nhà để xe trong nhà",
    "garage/outdoor-nhà để xe ngoài trời",
    "gas_station-trạm xăng",
    "gazebo/exterior-lều ngoài trời",
    "general_store/indoor-cửa hàng tổng hợp trong nhà",
    "general_store/outdoor-cửa hàng tổng hợp ngoài trời",
    "gift_shop-cửa hàng quà tặng",
    "glacier-sông băng",
    "golf_course-sân golf",
    "greenhouse/indoor-nhà kính trong nhà",
    "greenhouse/outdoor-nhà kính ngoài trời",
    "grotto-hang động",
    "gymnasium/indoor-phòng thể dục trong nhà",
    "hangar/indoor-nhà chứa máy bay trong nhà",
    "hangar/outdoor-nhà chứa máy bay ngoài trời",
    "harbor-cảng",
    "hardware_store-cửa hàng dụng cụ",
    "hayfield-cánh đồng cỏ khô",
    "heliport-sân đậu trực thăng",
    "highway-đường cao tốc",
    "home_office-văn phòng tại nhà",
    "home_theater-rạp chiếu phim tại nhà",
    "hospital-bệnh viện",
    "hospital_room-phòng bệnh viện",
    "hot_spring-suối nước nóng",
    "hotel/outdoor-khách sạn ngoài trời",
    "hotel_room-phòng khách sạn",
    "house-nhà",
    "hunting_lodge/outdoor-nhà săn ngoài trời",
    "ice_cream_parlor-quán kem",
    "ice_floe-tảng băng trôi",
    "ice_shelf-mảng băng trôi",
    "ice_skating_rink/indoor-sân trượt băng trong nhà",
    "ice_skating_rink/outdoor-sân trượt băng ngoài trời",
    "iceberg-núi băng trôi",
    "igloo-nhà băng",
    "industrial_area-khu công nghiệp",
    "inn/outdoor-nhà trọ ngoài trời",
    "islet-hòn đảo nhỏ",
    "jacuzzi/indoor-bồn tắm nước nóng trong nhà",
    "jail_cell-phòng giam",
    "japanese_garden-vườn Nhật Bản",
    "jewelry_shop-cửa hàng trang sức",
    "junkyard-bãi phế liệu",
    "kasbah-thành trì",
    "kennel/outdoor-chuồng chó ngoài trời",
    "kindergarden_classroom-lớp học mẫu giáo",
    "kitchen-nhà bếp",
    "lagoon-đầm phá",
    "lake/natural-hồ tự nhiên",
    "landfill-bãi rác",
    "landing_deck-boong hạ cánh",
    "laundromat-tiệm giặt ủi",
    "lawn-bãi cỏ",
    "lecture_room-phòng giảng",
    "legislative_chamber-phòng họp lập pháp",
    "library/indoor-thư viện trong nhà",
    "library/outdoor-thư viện ngoài trời",
    "lighthouse-ngọn hải đăng",
    "living_room-phòng khách",
    "loading_dock-bến xếp hàng",
    "lobby-sảnh chờ",
    "lock_chamber-buồng khóa",
    "locker_room-phòng thay đồ",
    "mansion-biệt thự",
    "manufactured_home-nhà sản xuất",
    "market/indoor-chợ trong nhà",
    "market/outdoor-chợ ngoài trời",
    "marsh-đầm lầy",
    "martial_arts_gym-phòng tập võ",
    "mausoleum-lăng mộ",
    "medina-khu phố cổ",
    "mezzanine-tầng lửng",
    "moat/water-hào nước",
    "mosque/outdoor-nhà thờ Hồi giáo ngoài trời",
    "motel-nhà nghỉ",
    "mountain-núi",
    "mountain_path-đường mòn núi",
    "mountain_snowy-núi tuyết",
    "movie_theater/indoor-rạp chiếu phim trong nhà",
    "museum/indoor-bảo tàng trong nhà",
    "museum/outdoor-bảo tàng ngoài trời",
    "music_studio-phòng thu âm",
    "natural_history_museum-bảo tàng lịch sử tự nhiên",
    "nursery-nhà trẻ",
    "nursing_home-nhà dưỡng lão",
    "oast_house-nhà sấy",
    "ocean-đại dương",
    "office-văn phòng",
    "office_building-tòa nhà văn phòng",
    "office_cubicles-buồng làm việc trong văn phòng",
    "oilrig-giàn khoan dầu",
    "operating_room-phòng mổ",
    "orchard-vườn cây ăn quả",
    "orchestra_pit-hố dàn nhạc",
    "pagoda-chùa",
    "palace-cung điện",
    "pantry-phòng để thực phẩm",
    "park-công viên",
    "parking_garage/indoor-gara đỗ xe trong nhà",
    "parking_garage/outdoor-gara đỗ xe ngoài trời",
    "parking_lot-bãi đỗ xe",
    "pasture-đồng cỏ",
    "patio-hiên nhà",
    "pavilion-đình, lều",
    "pet_shop-cửa hàng thú cưng",
    "pharmacy-nhà thuốc",
    "phone_booth-buồng điện thoại",
    "physics_laboratory-phòng thí nghiệm vật lý",
    "picnic_area-khu vực picnic",
    "pier-bến tàu",
    "pizzeria-tiệm pizza",
    "playground-sân chơi",
    "playroom-phòng chơi",
    "plaza-quảng trường",
    "pond-ao hồ",
    "porch-hiên nhà",
    "promenade-đường đi dạo",
    "pub/indoor-quán rượu trong nhà",
    "racecourse-trường đua",
    "raceway-đường đua",
    "raft-bè",
    "railroad_track-đường ray",
    "rainforest-rừng nhiệt đới",
    "reception-lễ tân",
    "recreation_room-phòng giải trí",
    "repair_shop-cửa hàng sửa chữa",
    "residential_neighborhood-khu dân cư",
    "restaurant-nhà hàng",
    "restaurant_kitchen-bếp nhà hàng",
    "restaurant_patio-sân nhà hàng",
    "rice_paddy-ruộng lúa",
    "river-sông",
    "rock_arch-vòm đá",
    "roof_garden-vườn trên mái",
    "rope_bridge-cầu treo",
    "ruin-tàn tích",
    "runway-đường băng",
    "sandbox-hố cát",
    "sauna-phòng xông hơi",
    "schoolhouse-trường học",
    "science_museum-bảo tàng khoa học",
    "server_room-phòng máy chủ",
    "shed-nhà kho",
    "shoe_shop-cửa hàng giày",
    "shopfront-mặt tiền cửa hàng",
    "shopping_mall/indoor-trung tâm thương mại trong nhà",
    "shower-vòi sen",
    "ski_resort-khu nghỉ dưỡng trượt tuyết",
    "ski_slope-dốc trượt tuyết",
    "sky-bầu trời",
    "skyscraper-tòa nhà chọc trời",
    "slum-khu ổ chuột",
    "snowfield-cánh đồng tuyết",
    "soccer_field-sân bóng đá",
    "stable-chuồng ngựa",
    "stadium/baseball-sân vận động bóng chày",
    "stadium/football-sân vận động bóng đá Mỹ",
    "stadium/soccer-sân vận động bóng đá",
    "stage/indoor-sân khấu trong nhà",
    "stage/outdoor-sân khấu ngoài trời",
    "staircase-cầu thang",
    "storage_room-phòng chứa đồ",
    "street-đường phố",
    "subway_station/platform-ga tàu điện ngầm",
    "supermarket-siêu thị",
    "sushi_bar-quán sushi",
    "swamp-đầm lầy",
    "swimming_hole-hố bơi",
    "swimming_pool/indoor-bể bơi trong nhà",
    "swimming_pool/outdoor-bể bơi ngoài trời",
    "synagogue/outdoor-giáo đường ngoài trời",
    "television_room-phòng xem TV",
    "television_studio-phòng thu hình",
    "temple/asia-đền chùa châu Á",
    "throne_room-phòng ngai vàng",
    "ticket_booth-quầy bán vé",
    "topiary_garden-vườn cây cảnh",
    "tower-tháp",
    "toyshop-cửa hàng đồ chơi",
    "train_interior-bên trong tàu",
    "train_station/platform-sân ga tàu",
    "tree_farm-trang trại cây",
    "tree_house-nhà trên cây",
    "trench-chiến hào",
    "tundra-lãnh nguyên",
    "underwater/ocean_deep-dưới nước/sâu trong đại dương",
    "utility_room-phòng tiện ích",
    "valley-thung lũng",
    "vegetable_garden-vườn rau",
    "veterinarians_office-văn phòng bác sĩ thú y",
    "viaduct-cầu cạn",
    "village-làng",
    "vineyard-vườn nho",
    "volcano-núi lửa",
    "volleyball_court/outdoor-sân bóng chuyền ngoài trời",
    "waiting_room-phòng chờ",
    "water_park-công viên nước",
    "water_tower-tháp nước",
    "waterfall-thác nước",
    "watering_hole-ao uống nước",
    "wave-sóng",
    "wet_bar-quầy bar",
    "wheat_field-cánh đồng lúa mì",
    "wind_farm-trang trại gió",
    "windmill-cối xay gió",
    "yard-sân",
    "youth_hostel-nhà trọ thanh niên",
    "zen_garden-vườn thiền",
]
let filterSpaceList = spaceList

const checkIconPath = ['../assets/icon/unchecked.png', '../assets/icon/check.png'] 
let chosenSpaceList = new Set()
let chosenFilterSpaceList = new Set()
let spaceContainer = document.getElementById('space-filter-list')
let spaceInput = document.getElementById('space-filter')
let spaceClear = document.getElementById('space-filter-clear')
let spaceOnly = document.getElementById("space-filter-only")
let checkOnly = false

const handleCheckSpace = (fullSpace, engSpace, checkIcon) => {
    if (checkIcon.getAttribute("src") === checkIconPath[0]) {
        chosenFilterSpaceList.add(fullSpace)
        chosenSpaceList.add(engSpace)
        checkIcon.setAttribute("src", checkIconPath[1])
    } else {
        chosenFilterSpaceList.delete(fullSpace)
        chosenSpaceList.delete(engSpace)
        checkIcon.setAttribute("src", checkIconPath[0])
    }
}

const showSpace = (spaceList) => {

    while(spaceContainer.lastChild) spaceContainer.removeChild(spaceContainer.lastChild)
    
    spaceList.forEach(space => {
        let [engSpace, vietSpace] = space.split("-")
        let spaceText = document.createElement("span")
        spaceText.className = 'space-filter-label normal-text'
        let spaceReplace = engSpace.replace("_", " ").split("/").map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(" / ") + " (" + vietSpace.charAt(0).toUpperCase() + vietSpace.slice(1) + ")"
        spaceText.innerHTML = spaceReplace
    
        let spaceWrapper = document.createElement("div")
        spaceWrapper.className = 'filter-wrapper'
    
        let checkIcon = document.createElement("img")
        checkIcon.className = 'filter-check-icon'
        checkIcon.src = chosenSpaceList.has(engSpace) ? checkIconPath[1] : checkIconPath[0]
        checkIcon.addEventListener("click", e => handleCheckSpace(space, engSpace, checkIcon))
    
        spaceWrapper.appendChild(spaceText)
        spaceWrapper.appendChild(checkIcon)
        spaceContainer.appendChild(spaceWrapper)
    })
}

const search = (value) => {
    return spaceList.filter((o) =>
        String(o).toLowerCase().includes(value.toLowerCase())
    )
}

showSpace(filterSpaceList)

spaceInput.addEventListener("input", e => {
    filterSpaceList = search(e.target.value)
    showSpace(filterSpaceList)
})

spaceClear.addEventListener("click", e => {
    spaceInput.value = null
    chosenSpaceList.clear()
    showSpace(filterSpaceList)
})

spaceOnly.addEventListener("click", e => {
    if (!checkOnly) showSpace(chosenFilterSpaceList)
    else showSpace(filterSpaceList)
    checkOnly = !checkOnly
})

export default chosenSpaceList